### ISSUE TITLE
Compatibility with lazy.nvim

### ISSUE THREAD

**Issue by GeoffreyBrunet** [joeveiga/ng.nvim#3]
Hello, installation with lazy.nvim don't works :)
<img width="381" alt="image" src="https://github.com/joeveiga/ng.nvim/assets/25690819/6bd7cc55-8457-4a0f-946b-76d798b0e0d1">

**Comment by joeveiga** [comment]
Hey @GeoffreyBrunet. I migrated my config to lazy.nvim a while ago and it's been working fine on my end since. Can you please share your config? Thank you
