### ISSUE TITLE
Code actions in template 

### ISSUE THREAD

**Issue by ziulev** [joeveiga/ng.nvim#5]
Hey there! Thank you very much for the plugin!
I have a question - how to achieve the following:

For example I have created a simple standalone component and in the template I put 
`{{someObsrvableVariable | async}}` it started complaining that there are no imports for the `async` pipe in the component which is awesome. 
But when I try to check code actions `lua vim.lsp.buf.code_action() ` it says that there are no any available actions 

But the expected behavior is to have “import …”

how to achieve this?

**Comment by joeveiga** [comment]
Hey @ziulev !

Those code actions come from the angular language server. That functionality would have to be implemented on their side, and then neovim (or any other lsp client such as vscode) would show that option automatically.

Luckily, it looks like there is already a PR for it https://github.com/angular/angular/pull/55595

Hopefully, that helps.
